#include "defines.h"

void InitOutput(void) {
    pinMode(RELAY_COMPRESSOR1, OUTPUT); //COMPRESSOR 01
    pinMode(RELAY_COMPRESSOR2, OUTPUT);//COMPRESSOR 02
    pinMode(OGP_OUT, OUTPUT); //OGP
    pinMode(LED_COMPRESSOR1, OUTPUT); //XC1
    pinMode(LED_COMPRESSOR2, OUTPUT);//XC2
    pinMode(LED_OGP, OUTPUT); //XOGP
    pinMode(ALARM, OUTPUT); //ALARME
  }
  void InitInput(void) {  
    pinMode(SUPERVISORIO, INPUT);  //FALTA DE FASE
    pinMode(AUTOMATIC, INPUT);  //CHAVE LIGA AUTOMATICO
    pinMode(EMERGENCY_BUTTON, INPUT);  //BOTAO DE EMERGENCIA   
    pinMode(COMPRESSOR_INPUT1, INPUT);  //COMPRESSOR 1 ENTRADA DIGITAL
    pinMode(COMPRESSOR_INPUT2, INPUT);  //COMPRESSOR 2 ENTRADA DIGITAL
  }